catalog_id: 'BaM17'
pageid_exclude_strings: []
pageid_regex: '.*?([0-9]{1,3}).*?'
figid_exclude_strings: []
figid_regex: '.*?([0-9]{1,3}).*?'
level_groups_regex: 'none'
patternHRID: [pub_name,figid_clean]
select_pdfpages: !!python/list
  - !!python/tuple [40,46]
  - !!python/tuple [76,77]
classlist: ['pageid', 'pageinfo']
figureclasslist: ['vesselprofilefigure']
figureidclasslist: ['figureid']
pageid_config: r'--psm 6 -c load_system_dawg=0 load_freq_dawg=0'