version: '3.5'

services:
  mining_shapes:
    container_name: shapes_mining
    build:
      context: ./
      network: host
      dockerfile: Dockerfile.CPU.dev
    ports:
      - '8888:8888' #for jupyter notebook
      - '6006:6006' #for tensorboard
      - '8000:8000' #for WebApp
    volumes:
      - ../:/home/Code
      #- /home/michael/Desktop/Ceramic_dataset/val:/home/images/val #train segmentation
      #- /home/michael/Desktop/Ceramic_dataset/valannot:/home/images/valannot #train segmentation
      - /home/michael/Desktop/tf_records:/home/tf_records #for splitrecords
      - /home/michael/Desktop/faster_rcnn_resnet101_coco_2018_01_28:/home/faster_rcnn_resnet101_coco_2018_01_28

      - /home/michael/Desktop/apply:/home/images/apply
      - /home/michael/Desktop/inference_graph_mining_pages_v8:/home/models/inference_graph_mining_pages_v8
      - /home/michael/Desktop/inference_graph_figureid_v1:/home/models/inference_graph_figureid_v1
      - /home/michael/Desktop/ResultRecord:/home/images/OUTPUT
      #segmentation model
      #- /home/michael/Desktop/Ceramic_dataset:/home/images/Ceramic_dataset
      #split traindata
      #- /home/michael/Downloads/20_Binary_Ceramic_Shapes:/home/images/20_Binary_Ceramic_Shapes
      - /home/michael/Downloads/miningshapes_cleaned/preliminary/results/:/home/images/source_imgs

      # anomaly detection
      - /home/michael/Downloads/Point_dataset_masked/:/home/images/point_dataset_masked

      #point detection
      - /home/michael/Downloads/OUTPUT_run1/:/home/images/OUTPUT_run1
      - /home/michael/Downloads/miningshapes_cleaned/:/home/images/mining_shapes

      #vscode extensions
      - ../vscode_remote/extensions/:/home/shape_miner/.vscode-server/extensions/
      - ../vscode_remote/insiders/:/home/shape_miner/.vscode-server-insiders/extensions/
      - ../vscode_remote/bashhistory:/commandhistory
    user: 1000:1000
    working_dir: /home/Code
    tty: true
